name: 'Install with retries'
description: 'Runs yarn install with up to 2 retries'
inputs:
  skip-cypress-binary:
    description: 'Whether to skip binary installation for cypress'
    required: false
    default: 'true'
  working-directory:
    description: 'Path to run `yarn install` at'
    required: false
    default: './'
runs:
  using: 'composite'
  steps:
    - name: Install cypress with binary
      if: steps.restore-cypress-cache.outputs.cache-hit != 'true'
      shell: bash
      run: ./install-with-retries.sh
      env:
        SKIP_CYPRESS_BINARY: ${{ inputs.skip-cypress-binary }}
      working-directory: ${{ inputs.working-directory }}
